#!/bin/bash

# Variable utilizada como código de retorno
returncode=0

# Controlo la cantidad de parámetros
if [ $# -eq 2 ]; then
   returncode=0
else
   if [ $# -eq 3 ]; then
      returncode=0
   else
      echo "ERROR DE PARÁMETROS"
      returncode=1
   fi
fi

#Controlo si origen y destino son iguales
if [ $1 = $2 -a $returncode -eq 0 ]; then
   echo "Origen y destino son iguales"
   returncode=2
fi

#Controlo si el archivo existe en el destino
existe="no"
if [ -f $2 -a $returncode -eq 0 ]; then
   echo "El archivo existe en el directorio destino"
   existe="si"
fi

#Extraigo el nombre del archivo de la ruta destino
if [ $returncode -eq 0 ]; then
   if [ $existe = "si" ]; then
      destino=$2
      tamanio=${#destino}
      fin=$tamanio
      i=`expr $tamanio - 1`

      while [ ${destino:$i:1} != "/" -a $i -ge 0 ] 
      do
         i=`expr $i - 1`
      done

      inicio=`expr $i + 1`
      #Compruebo si se puso ruta relavita o absoluta
      if [ $i -ge 0 ]; then
         ruta_dup=${2:0:$inicio}"dup/"${destino:$inicio:$fin}
         carpeta_dup=${2:0:$inicio}"dup"
      else
         ruta_dup="dup/"${destino:$inicio:$fin}
         carpeta_dup=${2:0:$inicio}"dup"
      fi

      #Controlo si existe la carpeta /dup
      if [ -d $carpeta_dup ]; then
         echo "Existe la carpeta $carpeta_dup"
      else
         mkdir $carpeta_dup
         if [ $? -ne 0 ]; then
            echo "Error en la creacion de la carpeta $carpeta_dup"
            returncode=3
         else
            echo "Se creo la carpeta $carpeta_dup"
         fi
      fi
   
   archivo_dup=$ruta_dup".000"

   #Controlo la existencia en la carpeta /dup
   if [ -f $archivo_dup ]; then
      cant=`expr $(ls $ruta_dup* | wc -w)`
      #Controlo la cantidad de archivos para agregar los ceros necesarios
      if [ $cant -le 9 ]; then
         ruta_dup=$ruta_dup".00"$cant
      else
         if [ $cant -le 99 ]; then
            ruta_dup=$ruta_dup".0"$cant
         else
            ruta_dup=$ruta_dup"."$cant
         fi
      fi
      mv $1 $ruta_dup
      if [ $? -ne 0 ]; then
         echo "Error al mover el archivo $1 a la carpeta de duplicados"
         returncode=4
      fi
   else
      ruta_dup=$ruta_dup".000"
      mv "$1"  "$ruta_dup"
      if [ $? -ne 0 ]; then
         echo "Error al mover el archivo $1 a la carpeta de duplicados" 
         returncode=4
      fi
   fi 
   else
   #Se realiza la copia porque estamos seguros que no se haya en el destino
      mv $1 $2
      if [ $? -ne 0 ]; then
         echo "Error al mover el archivo $1 a la carpeta destino"
         returncode=5
      fi
   fi
fi

if [ $returncode -eq 0 ]; then
   echo "Se movió el archivo correctamente desde: $1 hacia $2"
fi

if [ $returncode -eq 0 -a $# -eq 3 ]; then
   glog $3 "Mover exitoso desde: $1 hacia $2"
   echo "Se grabó en el log: $3"
fi
