#!/bin/bash

#Codigos de Retorno
OK=0
PERL_NO_INSTALADO=1
AMBIENTE_YA_INICILIZADO=2
ARCHIVO_PROV_NO_EXISTE=3
ARCHIVO_PRESUP_NO_EXISTE=4
DEMONIO_YA_ESTA_CORRIENDO=5

#inicializo el codigo de retorno
returncode=$OK

# ---------------------
# -- Checkeo de grupo --
# ---------------------
echo ""
echo "Verificando que Perl este instalado..."
vperl=`/usr/bin/perl -v`
vp1=`echo ${vperl#*[Vv]}`
vp2=`echo ${vp1%% *}`
version=`echo ${vp2%%.*}`
if [ -z $version ]; then
	version=0
fi

if [ $version -lt 5 ]; then
	clear
	echo ""
	echo "ERROR !:"
	echo ""
	echo "Este proceso de instalacion solo puede ser"
	echo "ejecutado si Perl 5 o superior esta instalado."
	echo ""
	echo "Efectue la instalacion de Perl"
	echo "e inicie nuevamente el procedimiento de instalacion."
	echo ""
	returncode=$PERL_NO_INSTALADO
else
	echo "FEPINI - Perl esta instalado correctamente"
fi
CURRDIR=$PWD

if [ $returncode -eq $OK ]; then
   if [ $GRUPO ]; then
      echo ""
      echo "FEPINI - La variable grupo ya está inicializada con el valor:  $GRUPO"
      returncode=$AMBIENTE_YA_INICILIZADO
   else
      #seteo el directorio del tp
#      GRUPO="/home/nscuri/repo/src"
	GRUPO="$CURRDIR/../"
   fi
fi

# Seteo la variables para ser utilizadas por los comandos
PATH_ARCH_MAEPRO="$GRUPO/pp/maepro.txt"
PATH_ARCH_PRESU="$GRUPO/pp/presu.txt"
PATH_PRESU_OLD="$GRUPO/pp/old"

PATH_ARRIBOS="$GRUPO/arribos"
PATH_FACT_RECIBIDAS="$GRUPO/recibidos"
PATH_FACT_RECHAZADAS="$GRUPO/rechazados"
PATH_FACT_ACEPTADAS="$GRUPO/aceptados"

PATH_ARCH_FACT_PAGAR="$GRUPO/facturas/apagar.txt"
PATH_ARCH_FACT_PAGAR_OLD="$GRUPO/facturas/old"

PATH_LISTADOS="$GRUPO/facturas/listados"
PATH_LOG="$GRUPO/comandos/log"
PATH_COMANDOS="$GRUPO/comandos"

cant=`expr $(ls $PATH_ARCH_MAEPRO | wc -w)`

if [ $returncode -eq $OK ]; then
   if [ $cant -eq 0 ]; then
      echo ""
      echo "FEPINI - Inicializacion de ambiente no fue exitosa. El archivo maestro de proveedores no existe"
      GRUPO=""
      returncode=$ARCHIVO_PROV_NO_EXISTE
   fi
fi

cant=`expr $(ls $PATH_ARCH_PRESU | wc -w)`

if [ $returncode -eq $OK ]; then
   if [ $cant -eq 0 ]; then
      echo ""
      echo "FEPINI - Inicializacion de ambiente no fie exitosa. El archivo de presupuesto no existe"
      GRUPO=""
      returncode=$ARCHIVO_PRESUP_NO_EXISTE
   fi
fi

if [ $returncode -eq $OK ]; then
   echo ""
   echo "**********************************************************"
   echo "*           Inicialización de Ambiente Concluída         *"
   echo "*                        Ambiente                        *"
   echo "**********************************************************"
   echo " GRUPO:                       $GRUPO"
   echo " PATH_ARCH_MAEPRO:            $PATH_ARCH_MAEPRO"
   echo " PATH_ARCH_PRESU:             $PATH_ARCH_PRESU"
   echo " PATH_PRESU_OLD:              $PATH_PRESU_OLD"
   echo " PATH_ARRIBOS:                $PATH_ARRIBOS"
   echo " PATH_FACT_RECIBIDAS:         $PATH_FACT_RECIBIDAS"
   echo " PATH_FACT_RECHAZADAS:        $PATH_FACT_RECHAZADAS"
   echo " PATH_FACT_ACEPTADAS:         $PATH_FACT_ACEPTADAS"
   echo " PATH_ARCH_FACT_PAGAR:        $PATH_ARCH_FACT_PAGAR"
   echo " PATH_ARCH_FACT_PAGAR_OLD:    $PATH_ARCH_FACT_PAGAR_OLD"
   echo " PATH_LISTADOS:               $PATH_LISTADOS"
   echo " PATH_LOG:                    $PATH_LOG"
   echo " PATH_COMANDOS:               $PATH_COMANDOS"
   echo "**********************************************************"

   # seteamos el PATH
   export PATH=$PATH:$comandos

   #exportamos las variables de entorno
   export GRUPO
   export PATH_ARCH_MAEPRO
   export PATH_ARCH_PRESU
   export PATH_PRESU_OLD
   export PATH_ARRIBOS
   export PATH_FACT_RECIBIDAS
   export PATH_FACT_RECHAZADAS
   export PATH_FACT_ACEPTADAS
   export PATH_ARCH_FACT_PAGAR
   export PATH_ARCH_FACT_PAGAR_OLD
   export PATH_LISTADOS
   export PATH_LOG
   export PATH_COMANDOS
fi

if [ $returncode -eq $OK ]; then
    cant=`expr $(ps -eo args | grep "feponio" | grep -v "startfe" | grep -v "stopfe" | grep -v grep | wc -l)`
    if [ $cant -eq 0 ]; then
#      echo "No se encuentra feponio corriendo."
      #Iniciamos el demonio
      startfe

		pid="$(ps -eo pid,args | grep "feponio" | grep -v "startfe" | grep -v "stopfe" | grep -v grep | cut -c1-6)"
		echo "----------------------------------------------------------"
		echo " FEPINI - Demonio corriendo bajo el no: $pid"
		echo "----------------------------------------------------------"
   else 
      echo ""
      echo "FEPINI - Inicializacion de ambiente no fue exitosa. El demonio feponio se encuentra corriendo."
      returncode=$DEMONIO_YA_ESTA_CORRIENDO
   fi
fi

 # exit $returncode
