#!/bin/bash
function truncar {
	let cant=`expr $(cat $logPathFilename | wc -l)`
	let dif=$cant-$TRUNC_SIZE
	aux=$logPathFilename"_temp"	
	let nroLinea=1
	IFS="
"
	for linea in `cat $logPathFilename`
	do
		if [ $nroLinea -gt $dif ]; then
			echo -e $linea >> $aux
		fi
		let nroLinea=$nroLinea+1
	done
	rm $logPathFilename
	mv $aux $logPathFilename
}
# Sintaxis de ejecucion: Glog <nombreComando> <mensaje> [tipoMensaje]
sintaxisEjecucion="Glog <nombreComando> <mensaje> [tipoMensaje]";
# Nombre comando.
modulo="Glog"
#Tamaño maximo (en cantidad de lineas)
MAX_SIZE=30
#Cantidad de registros a de jar al truncar el archivo
TRUNC_SIZE=10
# Tipo de mensaje default.
# I: Informativo
# W: Warning
# E: Error
# S: Error Severo
tipoMensaje="I";
separador=" - ";
fechaInstante=`date`;
# Si la cantidad de argumentos no cumple con la minima necesaria...
if [ "$#" -lt 2 ]; then
	tipoMensaje="E";
	mensaje="Sintaxis de ejecucion de comando incorrecta.";
	echo -e "$fechaInstante$separador$tipoMensaje$separador$mensaje";
	mensaje="Sintaxis: glog <nombreComando> <mensaje> [tipoMensaje]."
	echo -e "$fechaInstante$separador$tipoMensaje$separador$mensaje";
fi
# Si la cantidad de argumentos es dos, pues entonces se reciben argumentos <nombreComando> y <mensaje>;
# se utiliza tipoMensaje por default I (Informativo)...
if [ "$#" -eq 2 ]; then
	nombreComando=$1;
	mensaje=$2;
	mensajeLog="$fechaInstante$separador$tipoMensaje$separador$mensaje";
	longitudMensaje=`echo $mensajeLog | wc -c`;	
	logPathFilename=$PATH_LOG/$nombreComando;
	echo -e $mensajeLog >> $logPathFilename;
	let cant=`expr $(cat $logPathFilename | wc -l)`
	# Si la cantidad de lineas es mayo al tamaño maximo del archivo => lo trunca
	if [ $cant -gt $MAX_SIZE ]; then
		echo ""
		echo "GLOG - log $1 excedido"
		truncar
	fi
fi
# Si la cantidad de argumentos es 3, pues entonces se reciben argumentos <nombreComando>, <mensaje> y <tipoMensaje>...
if [ "$#" -eq 3 ]; then
	nombreComando=$1;
	mensaje=$2;
	logPathFilename=$PATH_LOG/$nombreComando;
	if [[ $3 = "I" || $3 = "W" || $3 = "E" || $3 = "S" ]]; then
		tipoMensaje=$3;
		mensajeLog="$fechaInstante$separador$tipoMensaje$separador$mensaje";
		longitudMensaje=`echo $mensajeLog | wc -c`;
		echo -e $mensajeLog >> $logPathFilename;
	else
		mensaje="Sintaxis de ejecucion de comando incorrecta.";
		echo -e "$fechaInstante$separador$tipoMensaje$separador$mensaje";
		mensaje="Verificar argumento <tipoMensaje>.";
		echo -e "$fechaInstante$separador$tipoMensaje$separador$mensaje";
	fi
	let cant=`expr $(cat $logPathFilename | wc -l)`
	# Si la cantidad de lineas es mayo al tamaño maximo del archivo => lo trunca
	if [ $cant -gt $MAX_SIZE ]; then
		echo ""
		echo "GLOG - log $1 excedido"
		truncar
	fi
fi
