#!/bin/bash

#
# Comando: Glog
# Autor: Mariano Quiroga
# Version: 1.0.0

# Sintaxis de ejecucion: Glog <nombreComando> <mensaje> [tipoMensaje]
sintaxisEjecucion="Glog <nombreComando> <mensaje> [tipoMensaje]";

# Nombre comando.
modulo="Glog"

# Ruta de archivos log.


# Tipo de mensaje default.
# I: Informativo
# W: Warning
# E: Error
# S: Error Severo

tipoMensaje="I";
separador="\t";

fechaInstante=`date`;

# Si la cantidad de argumentos no cumple con la minima necesaria...
if [ "$#" -lt 2 ]; then
	tipoMensaje="E";
	mensaje="Sintaxis de ejecucion de comando incorrecta.";
	echo -e "$fechaInstante$separador$tipoMensaje$separador$mensaje";
	mensaje="Sintaxis: glog <nombreComando> <mensaje> [tipoMensaje]."
	echo -e "$fechaInstante$separador$tipoMensaje$separador$mensaje";
fi

# Si la cantidad de argumentos es dos, pues entonces se reciben argumentos <nombreComando> y <mensaje>;
# se utiliza tipoMensaje por default I (Informativo)...
if [ "$#" -eq 2 ]; then
	nombreComando=$1;
	mensaje=$2;
	mensajeLog="$fechaInstante$separador$tipoMensaje$separador$mensaje";
	longitudMensaje=`echo $mensajeLog | wc -c`;	
	logPathFilename=$PATH_LOG$nombreComando;
		
	if [ $longitudMensaje -lt 132 ]; then 
		echo -e $mensajeLog >> $logPathFilename;
	else
		tipoMensaje="E";
		mensaje="Longitud de mensaje superior a 132 caracteres.";
		echo -e "$fechaInstante$separador$tipoMensaje$separador$mensaje";
	fi
fi

# Si la cantidad de argumentos es 3, pues entonces se reciben argumentos <nombreComando>, <mensaje> y <tipoMensaje>...
if [ "$#" -eq 3 ]; then
	nombreComando=$1;
	mensaje=$2;
	logPathFilename=$PATH_LOG$nombreComando;
	if [[ $3 = "I" || $3 = "W" || $3 = "E" || $3 = "S" ]]; then
		tipoMensaje=$3;
		mensajeLog="$fechaInstante$separador$tipoMensaje$separador$mensaje";
		longitudMensaje=`echo $mensajeLog | wc -c`;
		
		if [ $longitudMensaje -lt 132 ]; then 
			echo -e $mensajeLog >> $logPathFilename;
		else	
			tipoMensaje="E";
			mensaje="Longitud de mensaje superior a 132 caracteres.";
			echo -e "$fechaInstante$separador$tipoMensaje$separador$mensaje";
		fi
	else
		mensaje="Sintaxis de ejecucion de comando incorrecta.";
		echo -e "$fechaInstante$separador$tipoMensaje$separador$mensaje";
		mensaje="Verificar argumento <tipoMensaje>.";
		echo -e "$fechaInstante$separador$tipoMensaje$separador$mensaje";
	fi
fi

